//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brazucas.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    public partial class JOGOS
    {
        public JOGOS()
        {
            this.BOLAO = new HashSet<BOLAO>();
        }
    
        public int CODJOGO { get; set; }
        public Nullable<int> CODFASE { get; set; }
        public Nullable<int> CODESTADO { get; set; }
        public Nullable<int> CODCID { get; set; }
        public Nullable<int> SELECAO_A { get; set; }
        public Nullable<int> SELECAO_B { get; set; }
        public Nullable<System.DateTime> DATJOGO { get; set; }
        public Nullable<int> VENCJOGO { get; set; }
        public Nullable<int> PLACAR_A { get; set; }
        public Nullable<int> PLACAR_B { get; set; }
    
        public virtual ICollection<BOLAO> BOLAO { get; set; }
        public virtual CIDADE_SEDE CIDADE_SEDE { get; set; }
        public virtual ESTADO_JOGOS ESTADO_JOGOS { get; set; }
        public virtual FASE_JOGOS FASE_JOGOS { get; set; }
        public virtual JOGOS JOGOS1 { get; set; }
        public virtual JOGOS JOGOS2 { get; set; }
        public virtual SELECOES SELECOES { get; set; }
        public virtual SELECOES SELECOES1 { get; set; }

        public IQueryable<JOGOS> GetJogos(int id)
        {
            BrazucasEntities db = new BrazucasEntities();
            List<JOGOS> list = new List<JOGOS>();

            foreach (JOGOS item in db.JOGOS)
            {
                if (item.CODFASE == id)
                {
                    list.Add(new JOGOS
                    {
                        CODJOGO = item.CODJOGO,
                        CODFASE = item.CODFASE,
                        CODESTADO = item.CODESTADO,
                        CODCID = item.CODCID,
                        SELECAO_A = item.SELECAO_A,
                        SELECAO_B = item.SELECAO_B,
                        DATJOGO = item.DATJOGO,
                        VENCJOGO = item.VENCJOGO,
                        PLACAR_A = item.PLACAR_A,
                        PLACAR_B = item.PLACAR_B
                    });
                }
            }
            return list.AsQueryable();
        }
    }
}
