//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brazucas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANUNCIOS
    {
        public int CODANUN { get; set; }
        public Nullable<int> CODUSU { get; set; }
        public Nullable<int> CODCAT { get; set; }
        public Nullable<int> CODCID { get; set; }
        public string TITULOANUN { get; set; }
        public string DCRANUN { get; set; }
        public byte[] IMAGEANUN { get; set; }
        public Nullable<System.DateTime> DATPOSANUN { get; set; }
        public Nullable<System.DateTime> DATFIMANUN { get; set; }
    
        public virtual CATEGORIAS CATEGORIAS { get; set; }
        public virtual CIDADE_SEDE CIDADE_SEDE { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
