//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brazucas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BrazucasEntities : DbContext
    {
        public BrazucasEntities()
            : base("name=BrazucasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ANUNCIOS> ANUNCIOS { get; set; }
        public DbSet<BOLAO> BOLAO { get; set; }
        public DbSet<CATEGORIAS> CATEGORIAS { get; set; }
        public DbSet<CIDADE_SEDE> CIDADE_SEDE { get; set; }
        public DbSet<COMENTARIOS> COMENTARIOS { get; set; }
        public DbSet<ESTADO_JOGOS> ESTADO_JOGOS { get; set; }
        public DbSet<FASE_JOGOS> FASE_JOGOS { get; set; }
        public DbSet<JOGOS> JOGOS { get; set; }
        public DbSet<NOTICIAS> NOTICIAS { get; set; }
        public DbSet<PONTUACAO> PONTUACAO { get; set; }
        public DbSet<POSTOSVENDAS> POSTOSVENDAS { get; set; }
        public DbSet<RANKING> RANKING { get; set; }
        public DbSet<RODADA> RODADA { get; set; }
        public DbSet<SELECOES> SELECOES { get; set; }
        public DbSet<TIPO_USUARIOS> TIPO_USUARIOS { get; set; }
        public DbSet<USUARIOS> USUARIOS { get; set; }
    }
}
