//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brazucas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORIAS
    {
        public CATEGORIAS()
        {
            this.ANUNCIOS = new HashSet<ANUNCIOS>();
            this.NOTICIAS = new HashSet<NOTICIAS>();
        }
    
        public int CODCAT { get; set; }
        public string DCRCAT { get; set; }
    
        public virtual ICollection<ANUNCIOS> ANUNCIOS { get; set; }
        public virtual ICollection<NOTICIAS> NOTICIAS { get; set; }
    }
}
