//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brazucas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIDADE_SEDE
    {
        public CIDADE_SEDE()
        {
            this.ANUNCIOS = new HashSet<ANUNCIOS>();
            this.JOGOS = new HashSet<JOGOS>();
            this.POSTOSVENDAS = new HashSet<POSTOSVENDAS>();
        }
    
        public int CODCID { get; set; }
        public string NOMCID { get; set; }
        public string HISTORIA { get; set; }
    
        public virtual ICollection<ANUNCIOS> ANUNCIOS { get; set; }
        public virtual ICollection<JOGOS> JOGOS { get; set; }
        public virtual ICollection<POSTOSVENDAS> POSTOSVENDAS { get; set; }
    }
}
