//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brazucas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADO_JOGOS
    {
        public ESTADO_JOGOS()
        {
            this.JOGOS = new HashSet<JOGOS>();
        }
    
        public int CODESTADO { get; set; }
        public string DCRESTADO { get; set; }
    
        public virtual ICollection<JOGOS> JOGOS { get; set; }
    }
}
