//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brazucas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FASE_JOGOS
    {
        public FASE_JOGOS()
        {
            this.JOGOS = new HashSet<JOGOS>();
            this.RODADA = new HashSet<RODADA>();
        }
    
        public int CODFASE { get; set; }
        public string DCRFASE { get; set; }
    
        public virtual ICollection<JOGOS> JOGOS { get; set; }
        public virtual ICollection<RODADA> RODADA { get; set; }
    }
}
