//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brazucas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PONTUACAO
    {
        public PONTUACAO()
        {
            this.RANKING = new HashSet<RANKING>();
        }
    
        public int CODPONT { get; set; }
        public string DCRPONT { get; set; }
    
        public virtual ICollection<RANKING> RANKING { get; set; }
    }
}
