//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brazucas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SELECOES
    {
        public SELECOES()
        {
            this.JOGOS = new HashSet<JOGOS>();
            this.JOGOS1 = new HashSet<JOGOS>();
        }
    
        public int CODSELE { get; set; }
        public string NOMSELE { get; set; }
        public Nullable<int> NUMTITSELE { get; set; }
        public string HISTORIA { get; set; }
        public byte[] ESCUDOSELE { get; set; }
    
        public virtual ICollection<JOGOS> JOGOS { get; set; }
        public virtual ICollection<JOGOS> JOGOS1 { get; set; }
    }
}
