//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brazucas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMENTARIOS
    {
        public int CODCOM { get; set; }
        public Nullable<int> CODUSU { get; set; }
        public Nullable<int> CODNOT { get; set; }
        public string DCRCOM { get; set; }
        public Nullable<System.DateTime> DATCOM { get; set; }
        public string SITUACOM { get; set; }
    
        public virtual NOTICIAS NOTICIAS { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
