//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brazucas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOLAO
    {
        public int CODRODADA { get; set; }
        public Nullable<int> CODJOGO { get; set; }
        public Nullable<int> CODUSU { get; set; }
        public Nullable<int> VENCJOGO { get; set; }
        public Nullable<System.DateTime> DATAPOSTA { get; set; }
        public Nullable<int> PLACAR_A { get; set; }
        public Nullable<int> PLACAR_B { get; set; }
    
        public virtual JOGOS JOGOS { get; set; }
        public virtual RODADA RODADA { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
