//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brazucas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOGOS
    {
        public JOGOS()
        {
            this.BOLAO = new HashSet<BOLAO>();
        }
    
        public int CODJOGO { get; set; }
        public Nullable<int> CODFASE { get; set; }
        public Nullable<int> CODESTADO { get; set; }
        public Nullable<int> CODCID { get; set; }
        public Nullable<int> SELECAO_A { get; set; }
        public Nullable<int> SELECAO_B { get; set; }
        public Nullable<System.DateTime> DATJOGO { get; set; }
        public Nullable<int> VENCJOGO { get; set; }
        public Nullable<int> PLACAR_A { get; set; }
        public Nullable<int> PLACAR_B { get; set; }
    
        public virtual ICollection<BOLAO> BOLAO { get; set; }
        public virtual CIDADE_SEDE CIDADE_SEDE { get; set; }
        public virtual ESTADO_JOGOS ESTADO_JOGOS { get; set; }
        public virtual FASE_JOGOS FASE_JOGOS { get; set; }
    }
}
