//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brazucas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RANKING
    {
        public int CODRAN { get; set; }
        public Nullable<int> CODUSU { get; set; }
        public Nullable<int> CODRODADA { get; set; }
        public Nullable<int> CODPONT { get; set; }
    
        public virtual PONTUACAO PONTUACAO { get; set; }
        public virtual RODADA RODADA { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
