//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brazucas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RODADA
    {
        public RODADA()
        {
            this.RANKING = new HashSet<RANKING>();
        }
    
        public int CODRODADA { get; set; }
        public Nullable<int> CODFASE { get; set; }
        public string DCRTIPUSU { get; set; }
    
        public virtual BOLAO BOLAO { get; set; }
        public virtual FASE_JOGOS FASE_JOGOS { get; set; }
        public virtual ICollection<RANKING> RANKING { get; set; }
    }
}
