//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brazucas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public USUARIOS()
        {
            this.ANUNCIOS = new HashSet<ANUNCIOS>();
            this.BOLAO = new HashSet<BOLAO>();
            this.COMENTARIOS = new HashSet<COMENTARIOS>();
            this.NOTICIAS = new HashSet<NOTICIAS>();
            this.RANKING = new HashSet<RANKING>();
        }
    
        public int CODUSU { get; set; }
        public Nullable<int> CODTIPUSU { get; set; }
        public string NOMUSU { get; set; }
        public string EMAILUSU { get; set; }
        public string SEXUSU { get; set; }
        public Nullable<System.DateTime> DATNASCUSU { get; set; }
        public string LOGINUSU { get; set; }
        public string SENHAUSU { get; set; }
        public Nullable<decimal> CPFCNPJUSU { get; set; }
        public Nullable<decimal> TELUSU { get; set; }
    
        public virtual ICollection<ANUNCIOS> ANUNCIOS { get; set; }
        public virtual ICollection<BOLAO> BOLAO { get; set; }
        public virtual ICollection<COMENTARIOS> COMENTARIOS { get; set; }
        public virtual ICollection<NOTICIAS> NOTICIAS { get; set; }
        public virtual ICollection<RANKING> RANKING { get; set; }
        public virtual TIPO_USUARIOS TIPO_USUARIOS { get; set; }
    }
}
